### ISSUE TITLE
How to get the output

### ISSUE THREAD

**Issue by ortix** [HQarroum/middleware-chain#7]
So when I handle the chain, how do I get the output of the chain after all the functions have been run?

**Comment by HQarroum** [comment]
Hi,
Thanks for your interest! You have 2 architectural choices here.

1. The first reason I made this module was to be able to build [Express](https://expressjs.com/fr/)-like applications, but without Express. In that case, the complete flow of my application is managed by the middleware chain, and the app is just a sequence of middlewares interacting with the `input` and the `output`.

2. When you call `handle` you can always pass a callback in the output object:

```js
/**
 * A function to be called when the chain is completed.
 */
const callback = (err, message) => {
   if (err) {
      return console.log(`An error occurred : ${err}`);
   } 
   console.log(`Chain has completed : ${message}`);
};

// Starting a new chain.
chain.handle(input, { callback });
```

This way, in your middlewares you can call `output.callback` when appropriate (an error happened, or the chain has successfully completed).

**Comment by HQarroum** [comment]
Hi,
Did the answer help you ? In that case can I close the issue ?

**Comment by ortix** [comment]
Yes, sorry I didn't respond! You can close it
